kumuluzee:
  name: images-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImagesDS
      connection-url: ${PG_HOST}
      username: ${PG_USER}
      password: ${PG_PASSWORD}
      pool:
        max-size: 1
  config:
    consul:
      agent: ${CONSUL_HOST}
  health:
    checks:
      data-source-health-check:
        type: readiness
        jndi-name: jdbc/ImagesDS
  cors-filter:
    servlet:
      allow-origin: "*"
  streaming:
    kafka:
      producer:
        bootstrap-servers: sulky-01.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: newer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="h2ihozli" password="7RJbPr-cyeB7078BpmGO_E2KDlU7-8Ed";

